# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ad1b6cbe8c7e8c597ca491d076ef79e1318c4b466f5bafcf3bb07aad71a6cd8da7ddc083873b52bd87a3e7462dd9fee948cf681feba13ff5cea3b26169dee4

test:
  secret_key_base: 97f20811d3818fb15c5e31d32bb52efac4d3708caa7e216a92abf1b6d0df0f15d1f8215a727f5c35be7808b3e7da57259e98efe1935e58ab7d17505e40dbcea9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
